language: node_js
node_js:
  - "10"
script:
  - npx quasar build
cache:
  directories:
    - "node_modules"
notifications:
  email: true
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist/spa
  github-token: $GITHUB_TOKEN
  repo: yemolai/vuejs-norte.github.io
  keep-history: true
  target-branch: master
  on:
    branch: dev